cities = [
	"Balkh", 
	"Khost", 
	"Mazari Sharif", 
	"Durr�s", 
	"Kor��", 
	"Vlor�", 
	"Elbasan", 
	"Shkod�r", 
	"Gjirokast�r", 
	"Tirana", 
	"Adrar", 
	"Gharda�a", 
	"Oran", 
	"Algiers", 
	"Hassi Messaoud", 
	"Ouargla", 
	"B�char", 
	"In Salah", 
	"Tamanrasset", 
	"Constantine", 
	"M'sila", 
	"Tindouf", 
	"Andorra La Vella", 
	"Cabinda", 
	"Luanda", 
	"Codrington (Barbuda)", 
	"Saint John's (Antigua)", 
	"Bariloche", 
	"La Rioja", 
	"Salta", 
	"Bragado", 
	"Mar del Plata", 
	"San Juan", 
	"Buenos Aires", 
	"Mendoza", 
	"Santa Fe", 
	"Comodoro Rivadavia", 
	"Neuqu�n", 
	"Santa Rosa", 
	"C�rdoba", 
	"Paran�", 
	"Santiago del Estero", 
	"Corrientes", 
	"Posadas", 
	"Tandil", 
	"Esquel", 
	"Puerto Deseado", 
	"Tucum�n", 
	"Gualeguaych�", 
	"Rawson", 
	"Ushuaia", 
	"Jujuy", 
	"Resistencia", 
	"Viedma", 
	"Jun�n", 
	"R�o Gallegos", 
	"Z�rate", 
	"La Plata", 
	"Rosario", 
	"Gyumri", 
	"Yeghegnadzor", 
	"Vanadzor", 
	"Yerevan", 
	"Aberdeen", 
	"Eden", 
	"Mount Gambier", 
	"Adelaide", 
	"Esperance", 
	"Mount Isa", 
	"Albany", 
	"Eucla", 
	"Mudgee", 
	"Albury", 
	"Exmouth", 
	"Newcastle", 
	"Alice Springs", 
	"Frankston", 
	"Newman", 
	"Ararat", 
	"Geelong", 
	"Norah Head", 
	"Armidale", 
	"Geraldton", 
	"Nowra", 
	"Bairnsdale", 
	"Gold Coast", 
	"Oodnadatta", 
	"Ballarat", 
	"Gordonvale", 
	"Orange", 
	"Ballina", 
	"Gosford", 
	"Pennant Hills", 
	"Bathurst", 
	"Goulburn", 
	"Penrith", 
	"Bendigo", 
	"Grafton", 
	"Perth", 
	"Blacktown", 
	"Griffith", 
	"Port Hedland", 
	"Bourke", 
	"Halls Creek", 
	"Port Lincoln", 
	"Bowral", 
	"Hervey Bay", 
	"Rockhampton", 
	"Brisbane", 
	"Hobart", 
	"Roma", 
	"Broome", 
	"Horsham", 
	"Samford", 
	"Bunbury", 
	"Ipswich", 
	"Shepparton", 
	"Bundaberg", 
	"Kalgoorlie", 
	"St Arnaud", 
	"Byron Bay", 
	"Karratha", 
	"Sunshine Coast", 
	"Cairns", 
	"Katherine", 
	"Sydney", 
	"Campbelltown", 
	"Katoomba", 
	"Tamworth", 
	"Canberra", 
	"Kiama", 
	"Tennant Creek", 
	"Canterbury", 
	"Kyneton", 
	"Toowoomba", 
	"Carnarvon", 
	"Launceston", 
	"Torrensville", 
	"Ceduna", 
	"Leeton", 
	"Townsville", 
	"Charleville", 
	"Lindeman Island", 
	"Traralgon", 
	"Charters Towers", 
	"Lismore", 
	"Tweed Heads", 
	"Cobar", 
	"Longreach", 
	"Uluru", 
	"Coffs Harbour", 
	"Lord Howe Island", 
	"Wagga Wagga", 
	"Coober Pedy", 
	"Mackay", 
	"Warragul", 
	"Currie", 
	"Macquarie Island", 
	"Warrnambool", 
	"Curtin Springs", 
	"Mandurah", 
	"Weipa", 
	"Dalby", 
	"Melbourne", 
	"Whyalla", 
	"Darlinghurst", 
	"Melton", 
	"Wodonga", 
	"Darwin", 
	"Mildura", 
	"Wollongong", 
	"Dubbo", 
	"Moree", 
	"Echuca", 
	"Mosman", 
	"Amstetten", 
	"Horn", 
	"Ried im Innkreis", 
	"Ansfelden", 
	"Imst", 
	"Rohrbach", 
	"Bad Ischl", 
	"Innsbruck", 
	"Rust", 
	"Bad Radkersburg", 
	"Jennersdorf", 
	"Saalfelden am Steinernen Meer", 
	"Bad V�slau", 
	"Judenburg", 
	"Salzburg", 
	"Baden", 
	"Kapfenberg", 
	"Sch�rding", 
	"Bischofshofen", 
	"Kirchdorf an der Krems", 
	"Scheibbs", 
	"Bludenz", 
	"Kitzb�hel", 
	"Schwaz", 
	"Braunau am Inn", 
	"Klagenfurt", 
	"Schwechat", 
	"Bregenz", 
	"Klosterneuburg", 
	"S�lden", 
	"Bruck an der Leitha", 
	"Knittelfeld", 
	"Spittal an der Drau", 
	"Bruck an der Mur", 
	"Korneuburg", 
	"St. Andr�", 
	"Brunn am Gebirge", 
	"Krems", 
	"St. Johann im Pongau", 
	"Deutschlandsberg", 
	"Kufstein", 
	"St. Johann in Tirol", 
	"Dornbirn", 
	"Landeck", 
	"St. P�lten", 
	"Eferding", 
	"Leibnitz", 
	"St. Veit an der Glan", 
	"Eisenstadt", 
	"Leoben", 
	"Steyr", 
	"Enns", 
	"Leonding", 
	"Stockerau", 
	"Feldbach", 
	"Lienz", 
	"Tamsweg", 
	"Feldkirch", 
	"Liezen", 
	"Telfs", 
	"Feldkirchen in K�rnten", 
	"Lilienfeld", 
	"Ternitz", 
	"Freistadt", 
	"Linz", 
	"Traiskirchen", 
	"F�rstenfeld", 
	"Lustenau", 
	"Traun", 
	"G�nserndorf", 
	"Marchtrenk", 
	"Tulln an der Donau", 
	"Gerasdorf bei Wien", 
	"Mattersburg", 
	"Vienna", 
	"Gm�nd", 
	"Mayrhofen", 
	"Villach", 
	"Gmunden", 
	"Melk", 
	"V�cklabruck", 
	"G�tzis", 
	"Mistelbach", 
	"Voitsberg", 
	"Graz", 
	"M�dling", 
	"V�lkermarkt", 
	"Grieskirchen", 
	"Murau", 
	"Waidhofen an der Thaya", 
	"Gr�bming", 
	"M�rzzuschlag", 
	"Waidhofen an der Ybbs", 
	"G�ssing", 
	"Neunkirchen", 
	"Wals-Siezenheim", 
	"Hall in Tirol", 
	"Neusiedl am See", 
	"Weiz", 
	"Hallein", 
	"Oberpullendorf", 
	"Wels", 
	"Hard", 
	"Oberwart", 
	"Wiener Neustadt", 
	"Hartberg", 
	"Perchtoldsdorf", 
	"Wolfsberg", 
	"Hermagor-Pressegger See", 
	"Perg", 
	"W�rgl", 
	"Hohenems", 
	"Rankweil", 
	"Zell am See", 
	"Hollabrunn", 
	"Reutte", 
	"Zwettl", 
	"Aghjabadi", 
	"Lankaran", 
	"Shamakhi", 
	"Baku", 
	"Mingachevir", 
	"Shirvan", 
	"Ganja", 
	"Nakhchivan", 
	"Sumqayit", 
	"Khachmaz", 
	"Shaki", 
	"Freeport", 
	"Nassau", 
	"Manama", 
	"Riffa", 
	"Bogra", 
	"Dinajpur", 
	"Saidpur", 
	"Chandpur", 
	"Ishwardi", 
	"Sunamganj", 
	"Chittagong", 
	"Khulna", 
	"Sylhet", 
	"Comilla", 
	"Pabna", 
	"Tangail", 
	"Dhaka", 
	"Rajshahi", 
	"Bridgetown", 
	"Babruysk", 
	"Gomel", 
	"Polotsk", 
	"Baranovichi", 
	"Grodno", 
	"Salihorsk", 
	"Barysaw", 
	"Minsk", 
	"Vitebsk", 
	"Brest (Belarus)", 
	"Mogilev", 
	"Aalst", 
	"Dendermonde", 
	"Li�ge", 
	"Antwerp", 
	"Eupen", 
	"Marche-en-Famenne", 
	"Arlon", 
	"Ghent", 
	"Mechelen", 
	"Bruges", 
	"Hasselt", 
	"Mons", 
	"Brussels", 
	"Kortrijk", 
	"Namur", 
	"Charleroi", 
	"Leuven", 
	"Spa", 
	"Belize City", 
	"Dangriga", 
	"Punta Gorda", 
	"Belmopan", 
	"Orange Walk Town", 
	"San Pedro (Belize)", 
	"Bohicon", 
	"Kandi", 
	"Porto Novo", 
	"Cotonou", 
	"Natitingou", 
	"Sav�", 
	"Djougou", 
	"Parakou", 
	"Paro", 
	"Samdrup Jongkhar", 
	"Thimphu", 
	"Cochabamba", 
	"Riberalta", 
	"Trinidad", 
	"La Paz", 
	"Santa Cruz", 
	"Oruro", 
	"Tarija", 
	"Gaborone", 
	"Lobatse", 
	"Kanye", 
	"Molepolole", 
	"Alagoinhas", 
	"Goi�nia", 
	"Porto Acre", 
	"An�polis", 
	"Guarulhos", 
	"Porto Velho", 
	"Balne�rio Cambori�", 
	"Ilha de Itamarac�", 
	"Recife", 
	"Bel�m", 
	"Ilh�us", 
	"Ribeir�o Pr�to", 
	"Belo Horizonte", 
	"Joinville", 
	"Rio Branco", 
	"Blumenau", 
	"Juiz de Fora", 
	"Rio de Janeiro", 
	"Boa Vista", 
	"Londrina", 
	"Rio Grande", 
	"Brasilia", 
	"Maca�", 
	"Salvador", 
	"Cama�ari", 
	"Macap�", 
	"Santar�m", 
	"Campinas", 
	"Macei�", 
	"Santos", 
	"Campo Grande", 
	"Manaus", 
	"S�o Jos� dos Campos", 
	"Cruzeiro do Sul", 
	"Montes Claros", 
	"S�o Luis", 
	"Cuiab�", 
	"Natal", 
	"S�o Paulo", 
	"Curitiba", 
	"Niter�i", 
	"Sorocaba", 
	"Dourados", 
	"Ol�mpia", 
	"Tabatinga", 
	"Feira de Santana", 
	"Palmas", 
	"Tef�", 
	"Fernando de Noronha", 
	"Pelotas", 
	"Teresina", 
	"Florian�polis", 
	"Petr�polis", 
	"Uberl�ndia", 
	"Fortaleza", 
	"Pirassununga", 
	"Volta Redonda", 
	"Foz do Igua�u", 
	"Ponta Grossa", 
	"Bandar Seri Begawan", 
	"Kuala Belait", 
	"Pekan Tutong", 
	"Bansko", 
	"Razgrad", 
	"Troyan", 
	"Borovets", 
	"Ruse", 
	"Varna", 
	"Burgas", 
	"Sliven", 
	"Vidin", 
	"Kavarna", 
	"Sofia", 
	"Zlatni pyasatsi", 
	"Pleven", 
	"Stara Zagora", 
	"Plovdiv", 
	"Sunny Beach", 
	"Bobo-Dioulasso", 
	"Fada N'gourma", 
	"Ouahigouya", 
	"D�dougou", 
	"Koudougou", 
	"Bujumbura", 
	"Muyinga", 
	"Rutana", 
	"Gitega", 
	"Ngozi", 
	"Ruyigi", 
	"Battambang", 
	"Kampong Chhnang", 
	"Phnom Penh", 
	"Douala", 
	"Garoua", 
	"Abbotsford", 
	"Haldimand", 
	"Qikiqtarjuaq", 
	"Ajax", 
	"Halifax", 
	"Qu�bec", 
	"Aklavik", 
	"Hall Beach", 
	"Quesnel", 
	"Annapolis County", 
	"Halton Hills", 
	"Quispamsis", 
	"Arviat", 
	"Hamilton", 
	"Rae-Edzo", 
	"Atikokan", 
	"Happy Valley-Goose Bay", 
	"Rainy River", 
	"Baker Lake", 
	"Hay River", 
	"Rankin Inlet", 
	"Banff", 
	"High Level", 
	"Red Deer", 
	"Barrie", 
	"Hopedale", 
	"Regina", 
	"Bathurst", 
	"Huntsville", 
	"Renfrew", 
	"B�cancour", 
	"Igloolik", 
	"Repentigny", 
	"Bella Coola", 
	"Inukjuak", 
	"Resolute Bay", 
	"Belleville", 
	"Inuvik", 
	"Richmond", 
	"Blanc-Sablon", 
	"Iqaluit", 
	"Richmond Hill", 
	"Brampton", 
	"Joliette", 
	"Rimouski", 
	"Brandon", 
	"Kamloops", 
	"Riverview", 
	"Brantford", 
	"Kawartha Lakes", 
	"Rocky Mountain House", 
	"Brockville", 
	"Kelowna", 
	"Rothesay", 
	"Burlington", 
	"Kenora", 
	"Rouyn-Noranda", 
	"Burnaby", 
	"Kentville", 
	"Saanich", 
	"Caledon", 
	"Keremeos", 
	"Saguenay", 
	"Calgary", 
	"Kings County", 
	"Saint-Georges", 
	"Cambridge", 
	"Kingston", 
	"Saint-Hyacinthe", 
	"Cambridge Bay", 
	"Kirkland Lake", 
	"Saint-Jean-sur-Richelieu", 
	"Campbell River", 
	"Kitchener", 
	"Saint-J�r�me", 
	"Campbellton", 
	"Kugaaruk", 
	"Saint John (CA - NB)", 
	"Camrose", 
	"Kugluktuk", 
	"Salaberry-de-Valleyfield", 
	"Cap-aux-Meules", 
	"Kuujjuaq", 
	"Salmon Arm", 
	"Cape Breton Regional Municipality", 
	"La Ronge", 
	"Sarnia", 
	"Cape Dorset", 
	"Labrador City", 
	"Saskatoon", 
	"Carmacks", 
	"Langley", 
	"Sault Ste. Marie", 
	"Charlottetown", 
	"Laval", 
	"Sechelt", 
	"Chatham-Kent", 
	"Les Coteaux", 
	"Selkirk", 
	"Chemainus", 
	"Lethbridge", 
	"Sept-�les", 
	"Chetwynd", 
	"Levis", 
	"Shawinigan", 
	"Chezzetcook", 
	"Lloydminster (CA-AB)", 
	"Sheet Harbour", 
	"Chibougamau", 
	"Lloydminster (CA-SK)", 
	"Sherbrooke", 
	"Chilliwack", 
	"London", 
	"Sicamous", 
	"Churchill", 
	"Longueuil", 
	"Sidney", 
	"Clarington", 
	"Maple Ridge", 
	"Squamish", 
	"Clyde River", 
	"Markham", 
	"St. Albert", 
	"Comox", 
	"Mary's Harbour", 
	"St. Catharines", 
	"Conception Bay South", 
	"Matane", 
	"St. George's", 
	"Coquitlam", 
	"Mayo", 
	"St. John's (CA - NF)", 
	"Coral Harbour", 
	"MD of Lunenburg", 
	"St. Joseph", 
	"Corner Brook", 
	"Meadow Lake", 
	"St. Thomas", 
	"Cornwall", 
	"Medicine Hat", 
	"Steinbach", 
	"Cranbrook", 
	"Milton", 
	"Stephenville", 
	"Creighton", 
	"Miramichi", 
	"Stonewall", 
	"Creston", 
	"Mississauga", 
	"Stony Rapids", 
	"Crofton", 
	"Moncton", 
	"Stratford", 
	"Cumberland County", 
	"Montr�al", 
	"Strathcona County", 
	"Dauphin", 
	"Moose Jaw", 
	"Summerside", 
	"Dawson City (Yukon T.)", 
	"Morden", 
	"Surrey", 
	"Dawson Creek (Br. Col.)", 
	"Mount Pearl", 
	"Swan River", 
	"Deline", 
	"Nanaimo", 
	"Swift Current", 
	"Delta", 
	"Nelson", 
	"Taloyoak", 
	"Denare Beach", 
	"New Westminster", 
	"Temiskaming Shores", 
	"Dieppe", 
	"Newmarket", 
	"Terrebonne", 
	"Drummondville", 
	"Niagara Falls", 
	"The Pas", 
	"Dryden", 
	"Nipigon", 
	"Thompson", 
	"Duncan", 
	"Norfolk", 
	"Thunder Bay", 
	"East Hants", 
	"Norman Wells", 
	"Timmins", 
	"Edmonton", 
	"North Bay", 
	"Tofino", 
	"Elbow", 
	"Oakville", 
	"Toronto", 
	"Entwistle", 
	"Old Crow", 
	"Trail", 
	"Eureka", 
	"Orillia", 
	"Trois-Rivieres", 
	"Faro", 
	"Oshawa", 
	"Truro", 
	"Fort McPherson", 
	"Ottawa", 
	"Tsiigehtchic", 
	"Fort Nelson", 
	"Owen Sound", 
	"Tuktoyaktuk", 
	"Fort Smith", 
	"Paradise", 
	"Uxbridge", 
	"Fort St. John", 
	"Parksville", 
	"Vancouver", 
	"Fredericton", 
	"Paulatuk", 
	"Vaughan", 
	"Gander", 
	"Pembroke", 
	"Victoria", 
	"Gasp�", 
	"Penticton", 
	"Waterloo", 
	"Gatineau", 
	"Peterborough", 
	"Welland", 
	"Gjoa Haven", 
	"Pickering", 
	"Wetaskiwin", 
	"Glace Bay", 
	"Pickle Lake", 
	"Whistler", 
	"Goderich", 
	"Pictou", 
	"Whitby", 
	"Golden", 
	"Pond Inlet", 
	"White Rock", 
	"Granby", 
	"Ponoka", 
	"Whitehorse", 
	"Grand Falls-Windsor", 
	"Port Alberni", 
	"Williams Lake", 
	"Grand Forks", 
	"Port Coquitlam", 
	"Windsor", 
	"Grande Prairie", 
	"Port Hardy", 
	"Winnipeg", 
	"Gravenhurst", 
	"Portage la Prairie", 
	"Wood Buffalo", 
	"Greater Sudbury", 
	"Prince Albert", 
	"Yarmouth County", 
	"Greenwood", 
	"Prince George", 
	"Yellowknife", 
	"Guelph", 
	"Prince Rupert", 
	"Yorkton", 
	"Bangui", 
	"Bimbo", 
	"Berb�rati", 
	"Bozoum", 
	"Ab�ch�", 
	"N'Djamena", 
	"Sarh", 
	"Antofagasta", 
	"Iquique", 
	"Rancagua", 
	"Arica", 
	"La Serena", 
	"Santiago (Chile)", 
	"Chill�n", 
	"Osorno", 
	"Talcahuano", 
	"Concepci�n", 
	"Puerto Montt", 
	"Valpara�so", 
	"Coyhaique", 
	"Puerto Williams", 
	"Villarrica", 
	"Easter Island", 
	"Punta Arenas", 
	"Vi�a del Mar", 
	"Anshan", 
	"Hotan", 
	"Shenzhen", 
	"Baoding", 
	"Huaibei", 
	"Shigatse", 
	"Baotou", 
	"Huainan", 
	"Shijiazhuang", 
	"Bayi", 
	"Hulunbuir", 
	"Suzhou", 
	"Beijing", 
	"Jilin", 
	"Taiyuan", 
	"Benxi", 
	"Jinan", 
	"Tangshan", 
	"Chamdo", 
	"Jinzhou", 
	"Tianjin", 
	"Changchun", 
	"Kashgar", 
	"Turpan", 
	"Changde", 
	"Korla", 
	"�r�mqi", 
	"Changsha", 
	"Kunming", 
	"Weihai", 
	"Changzhou", 
	"Lanchow", 
	"Wuhan", 
	"Chengdu", 
	"Langfang", 
	"Wuhu", 
	"Chongqing", 
	"Leshan", 
	"Xi'an", 
	"Dalian", 
	"Lhasa", 
	"Xiamen", 
	"Dandong", 
	"Luoyang", 
	"Xianyang", 
	"Daqing", 
	"Mudanjiang", 
	"Xilinhot", 
	"Datong", 
	"Nagqu Town", 
	"Xining", 
	"Foochow", 
	"Nanchang", 
	"Xinmi", 
	"Foshan", 
	"Nanjing", 
	"Xinyang", 
	"Fushun", 
	"Nanning", 
	"Xuzhou", 
	"Golmud", 
	"Nantong", 
	"Yanji", 
	"Guangzhou", 
	"Ningbo", 
	"Yinchuan", 
	"Guilin", 
	"Pudong", 
	"Yumen", 
	"Guiyang", 
	"Qingdao", 
	"Zhangjiajie", 
	"Haikou", 
	"Qinhuangdao", 
	"Zhangjiakou", 
	"Hami", 
	"Qiqihar", 
	"Zhanjiang", 
	"Handan", 
	"Sanya", 
	"Zhengzhou", 
	"Hangzhou", 
	"Shanghai", 
	"Zhuhai", 
	"Harbin", 
	"Shantou", 
	"Zibo", 
	"Hefei", 
	"Shaoxing", 
	"Hohhot", 
	"Shenyang", 
	"Arauca", 
	"Ibagu�", 
	"Riohacha", 
	"Armenia", 
	"Leticia", 
	"Sabaneta", 
	"Barranquilla", 
	"Manizales", 
	"San Andr�s", 
	"Bogota", 
	"Medellin", 
	"San Juan de Pasto", 
	"Bucaramanga", 
	"Mocoa", 
	"Santa Marta", 
	"Buenaventura", 
	"Monter�a", 
	"Sincelejo", 
	"Cali", 
	"Neiva", 
	"Valledupar", 
	"Cartagena (Colombia)", 
	"Pereira", 
	"Villavicencio", 
	"C�cuta", 
	"Puerto Carre�o", 
	"Garagoa", 
	"Quibd�", 
	"Fomboni", 
	"Moroni", 
	"Alajuela", 
	"Lim�n", 
	"Liberia", 
	"San Jose (CR)", 
	"Abidjan", 
	"Daloa", 
	"San P�dro (Ivory C.)", 
	"Bouak�", 
	"Divo", 
	"Yamoussoukro", 
	"Dabakala", 
	"Korhogo", 
	"Bjelovar", 
	"Pula", 
	"Vara�din", 
	"Dubrovnik", 
	"Rijeka", 
	"Zadar",
]