name: Pylint

on:
  push:
    branches:
      - main  # Defina quais branches devem disparar a verificação
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Escolha a versão do Python desejada

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint  # Instala o pylint
        pip install -r requirements.txt  # Instala as dependências do projeto, se houver

    - name: Run Pylint
      run: |
        pylint your_package/  # Substitua pelo diretório do seu código
